service: hello-serverless-demo # NOTE: update this with your service name

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
# iamRoleStatements:
#   - Effect: "Allow"
#     Action: "ssm:GetParameters"
#     Resource:
#       - "*"

functions:
  - ${file(serverless/hello.yml)}
